import streamlit as st

st.title("데이터 분석 AI에 오신 여러분 환영합니다🎈🎉")
st.divider()
c1, c2, c3 = st.columns(3)

c1.header(":blue[데이터 전처리]", divider="blue")
c1.subheader("1. 데이터 불러오기")
c1.write("파이썬으로 데이터 불러오기.")
c1.subheader("2. 데이터 확인")
c1.write("가져온 데이터의 개수 및 자료형 확인.")
c1.subheader("3. 열 추출")
c1.write("분석에 필요한 열 데이터만 추출하기.")
c1.subheader("4. 행 추출")
c1.write("분석에 필요한 행 데이터만 추출하기.")
c1.subheader("5. 결측치 확인")
c1.write("결측 데이터 확인하기")
c1.subheader("6. 결측치 처리")
c1.write("결측 데이터 처리하기")
c2.header(":green[데이터 분석]", divider="green")
c2.subheader("1. 평균, 중앙, 최빈")
c2.write("평균, 중앙, 최빈값의 차이점을 이해하고 데이터에 적용해보기.")
c2.subheader("2. 분산과 표준편차")
c2.write("분산과 표준편차를 이해하고 데이터에 적용해보기.")
c2.subheader("3. 상관관계")
c2.write("상관관계를 이해하고 데이터에 적용해보기.")
c2.header(":orange[데이터 시각화]", divider="orange")
c2.subheader("📈 꺾은선 그래프")
c2.write("꺾은선 그래프를 이해하고 데이터를 시각화하기.")
c2.subheader("📊 막대 그래프")
c2.write("막대 그래프를 이해하고 데이터를 시각화하기.")
c2.subheader("🍩 원 그래프")
c2.write("원 그래프를 이해하고 데이터를 시각화하기.")
c2.subheader("📊 히스토그램")
c2.write("히스토그램을 이해하고 데이터를 시각화하기.")

c3.header(":red[데이터 실습하기]", divider="red")
c3.subheader('⚽ 데이터 운동장')
c3.write("분석할 데이터를 선택하거나 분석할 데이터 파일을 올려서 데이터를 분석하는 곳 입니다. 분석 할 데이터를 선택하고 전처리한 후 시각화 자료를 만들 수 있습니다.")


c3.header(":violet[인공지능 학습하기]", divider="violet")
c3.subheader('🧪 인공지능 실험실')
c3.write("데이터를 선택하고 신경망 모델을 설계할 수 있습니다. 예측할 데이터를 선택하고 인공지능 모델 학습에 필요한 신경망을 설계하고 학습시켜보세요! 여러분이 만든 신경망의 정확도는 얼마인가요?")

c3.subheader('🎠 인공지능 놀이터')
c3.write("당뇨병 데이터와 타이타닉 데이터를 이용해 생성한 인공지능 모델을 이용해 만든 프로그램입니다. 만약 내가 타이타닉에 탑승했다면 생존율은 얼마일까요?")
