import streamlit as st

st.title("데이터 운동장에 오신 여러분 환영합니다🎈🎉")
st.header(' 1. 데이터 운동장⚽')
st.subheader(" 1) 파일을 선택하거나 올릴수 있어요.")
st.write('CSV파일을 올릴 수 있어요.')
st.write('오류있는 데이터가 있는지 잘 확인해주세요.')
st.subheader(" 2) 데이터를 선택할 수 있어요.")
st.write("데이터의 행렬을 변경해야할 때는 행렬전환 체크박스를 선택해주세요.")
st.write("필요한 데이터의 열만 선택할 수 있습니다.")
st.subheader(" 3) 데이터를 시각화 할 수 있어요.")
st.write("line, bar, hist 그래프를 그릴 수 있어요.")
st.write("그래프를 그리기 위해 x, y 데이터를 선택해주세요.")
st.divider()

st.header('2. 인공지능 실험실🧪')
st.subheader("1) 데이터를 선택할 수 있어요")
st.write("현재 제공되는 데이터는 타이타닉 데이터와 당뇨병 데이터 2개가 있어요")
st.subheader("2) 필요한 데이터를 선택할 수 있어요.")
st.write("필요한 데이터의 열만 선택할 수 있어요")
st.write("데이터 정보를 통해 결측치를 확인하고 결측치가 있다면 제거해주세요.")
st.write("예측하고자하는 데이터는 예측항목으로 선택해주세요")
st.subheader('3) 신경망 모델을 디자인할 수 있어요.')
st.write('원핫인코딩 기능을 제공합니다.')
st.write('자신이 원하는 신경망 모델의 레이어 개수와 노드를 선택하세요.')
st.write('손실함수, 활성함수, 학습횟수를 선택할 수 있어요')
st.divider()
st.header('3. 인공지능 놀이터🎠')
st.subheader("데이터를 입력하여 결과를 예측할 수 있어요!")
st.write("내가 만약 타이타닉에 탑승했다면?")
st.write("내가 당뇨병에 걸릴 확률은?")